import 'styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
// import Font Awesome CSS
import "@fortawesome/fontawesome-svg-core/styles.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import {config} from "@fortawesome/fontawesome-svg-core";
import ModalContext from "context/Modal/index";
// Tell Font Awesome to skip adding the CSS automatically
// since it's already imported above
config.autoAddCss = false;

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">

      <body className={inter.className}>
      <ModalContext>
        {children}
        <ToastContainer toastClassName='toast-font' />
      </ModalContext>
      </body>

      </html>
  )
}
